### PR TITLE
Added a new "quiet" option

### PR DESCRIPTION
**Pull request by ckjbgames**
The option makes the debug option (and the rest of the program) produce less output.

### CODE REVIEW

**Comment by Wheatwizard** [comment]
If it is decided that we want a `-q` flag, it should automatically engage debug mode anyway, since `-q` currently doesn't do anything unless debug mode is on.  There is no case, I can forsee, in which you would want to use `-q` instead of `-qd`.

**Comment by ckjbgames** [comment]
Ok. Let me implement that

**Comment by ckjbgames** [comment]
Done

**Comment by DJMcMayhem** [comment]
I'm not really a fan of this flag. I think overall we have to many flags/modes, and this one doesn't seem significant enough to add, since it doesn't change any functionality. 

If you think there is too much debug output, I'd totally consider changing the debug output to be a little more succinct. But I think that should be a permanent change, not a new flag.

**Comment by Wheatwizard** [comment]
I agree with DJMcMayhem on this issue.  And so I am going to close this pull request.  That doesn't mean discussion is over, simply that the `-q` flag will not be added as is.  Feel free to voice any additional concerns.

**Comment by ckjbgames** [comment]
ok

**Pull request closed without merging**
