### PR TITLE
Update from master

### PR DESCRIPTION
**Pull request by Wheatwizard**
Updated with changes and bugfixes from the master so that we can begin development on the debug flags again.

### CODE REVIEW

**Comment by DJMcMayhem** [comment]
Hey, this is unrelated to this particular PR, but I thought you might appreciate it: http://codegolf.stackexchange.com/a/86157/31716

:smiley:

**Comment by Wheatwizard** [comment]
Cool!  If you would like an explanation of my modulus I would be happy to provide one.

Also, not to be nitpicky but in your explanation you mixed up push a zero and push negative one

**Comment by Wheatwizard** [comment]
Lastly I used a version of my optimizer to shorten your solution to 94 bytes.

`(({}<>))<>{({}[()])<>(({}[()])){{}(<({}[({})])>)}{}({}({}))<>}{}<>([{}]{}<(())>){((<{}{}>))}{}`

It is still your algorithm just my program figured out how to make it a bit shorter.

**Comment by DJMcMayhem** [comment]
Hmm, that doesn't seem to be working right. http://brain-flak.tryitonline.net/#code=KCh7fTw-KSk8Pnsoe31bKCldKTw-KCh7fVsoKV0pKXt7fSg8KHt9Wyh7fSldKT4pfXt9KHt9KHt9KSk8Pn17fTw-KChbe31de30pKXt7fXt9KDwoKCkpPil9e30&input=MTAwCjQ

But hey, if you can outgolf me, feel free to make an answer on that question! I love a little friendly competition!

**Comment by Wheatwizard** [comment]
Yeah I had a bug in my developmental version.  I have updated it to a working albeit longer version.

**Comment by 1000000000** [comment]
What else is left to do with the debug flags?

**Comment by Wheatwizard** [comment]
I was going to add a flag to display both stacks and a flag for code injection.  I intend to start an issue for this.

**Comment by 1000000000** [comment]
Ah cool, yeah that would be useful

**Comment by Wheatwizard** [comment]
I made some improvements on your answer to the divisibility problem.  Thought you would appreciate it:
http://codegolf.stackexchange.com/questions/86149/divisibility-test/86570#86570

**Pull request merged**
