### PR TITLE
Added Brain-Flak Optimizer

### PR DESCRIPTION
**Pull request by Wheatwizard**
I wrote a python script that takes a piece of Brain-Flak code and makes it smaller by using a number of rules.  New rules can be added to the theorems folder and selected in **init**.py.

### CODE REVIEW

**Comment by DJMcMayhem** [comment]
I'm not sure if this should go in the main branch. (Or the compressor while we're at it.) It's certainly a cool idea, but IMO the main branch should contain _just_ the interpreter, and some simple documentation. Why not create your own repo for this?

**Comment by Wheatwizard** [comment]
ok sure thing

**Comment by Wheatwizard** [comment]
I made a new repo.  It can be found here: github.com/Wheatwizard/Brain-Flak-Tools.

**Comment by Wheatwizard** [comment]
Oh, I forgot to say this but if you or Louis would like to be members on that repo just ask.  I'd be happy to add you.

**Pull request closed without merging**
