### PR TITLE
Fixed flag issue

### PR DESCRIPTION
**Pull request by Mega-Tom**
This is my solution to the flag issue. It should work now for all combinations of input and output types.

### CODE REVIEW

**Comment by Wheatwizard** [comment]
While this is not my favorite solution I think that it is better than the current one.  I am in favor of merging but leaving the issue open.

**Comment by Wheatwizard** [comment]
Also since this is a fairly big change and not a bug fix I might say its better to mark it as v1.2.0 rather than v1.1.2.

**Comment by 1000000000** [comment]
I'm still not sure its worth it to have an ASCII input mode that is exactly like the utf8 input mode except for throwing an error for characters > 255

**Comment by DJMcMayhem** [comment]
Yeah, I have to agree with 1000000000 here. It seems redundant to me.  Here's what makes the most sense to me:
- Default: Decimal input, Decimal output
- -a UTF8 input, decimal output
- -A decimal input, UTF8 output
- -c UTF8 input, UTF8 output

I think this makes the most sense because there's not really any good reason to restrict the IO to a smaller range when there is integer wrapping, and it can handle a much larger range.

I'd like to do this soon. Does anyone have objections?

**Pull request closed without merging**
